# Generated by Django 4.0.3 on 2022-03-10 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyHtmls',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('policy_html', models.TextField(blank=True, null=True)),
                ('policy_html_sha1', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'policy_htmls',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PolicyReaderViewHtmls',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('policy_reader_view_html', models.TextField(blank=True, null=True)),
                ('policy_reader_view_html_sha1', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'policy_reader_view_htmls',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PolicySnapshots',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('homepage_snapshot_url', models.TextField(blank=True, null=True)),
                ('policy_snapshot_url', models.TextField(blank=True, null=True)),
                ('policy_url', models.TextField(blank=True, null=True)),
                ('homepage_snapshot_redirected_url', models.TextField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('phase', models.TextField(blank=True, null=True)),
                ('file_type', models.TextField(blank=True, null=True)),
                ('policy_title', models.TextField(blank=True, null=True)),
                ('link_text', models.TextField(blank=True, null=True)),
                ('pdf_filename', models.TextField(blank=True, null=True)),
                ('classifier_probability', models.FloatField(blank=True, null=True)),
                ('analysis_subcorpus', models.IntegerField(blank=True, null=True)),
                ('parked_domain', models.IntegerField(blank=True, null=True)),
                ('cross_domain_homepage_redir', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'policy_snapshots',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PolicyTexts',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('policy_text', models.TextField(blank=True, null=True)),
                ('flesch_kincaid', models.FloatField(blank=True, null=True)),
                ('smog', models.FloatField(blank=True, null=True)),
                ('flesch_ease', models.TextField(blank=True, null=True)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('sha1', models.TextField(blank=True, null=True)),
                ('simhash', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'policy_texts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('domain', models.TextField(blank=True, null=True)),
                ('categories', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sites',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AlexaRanks',
            fields=[
                ('site_id', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='viewer.sites')),
                ('year', models.TextField(blank=True, null=True)),
                ('phase', models.TextField(blank=True, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'alexa_ranks',
                'managed': False,
            },
        ),
    ]
